const SPEAKER_FENCE_LABELS = new Set(['didascalia']);

/**
 * Select only text that can be attributed to the episode's speaker.
 *
 * A user-role episode is the full conversational payload: the sender's own
 * words plus fenced forwards, quotes, filenames, catalog data and document
 * material. Recall needs that whole payload; fact extraction does not. Mining
 * every fenced block with `speakerName=owner` turns "the owner showed me a
 * document saying X" into "the owner said X".
 *
 * Canonical fences are generated by `core/memory/spotlight.ts#fence` and carry
 * a fresh 12-hex nonce. A complete canonical fence is therefore structural
 * evidence that its body was deliberately separated from the surrounding
 * speaker text. We keep only the two fenced forms that are still the sender's
 * own expression:
 *
 * - `didascalia`: a non-forwarded attachment caption typed by the sender;
 * - Voice transcriptions are deliberately excluded: ingress classifies them
 *   as derived, not author-authored, because the speaker is not verified.
 *
 * Every other well-formed fence is excluded by default. That fail-closed
 * default matters for future ingress sources: adding a new fenced data source
 * cannot silently make it owner-authored memory merely because this function
 * was not updated at the same time.
 *
 * Malformed/unclosed marker-looking text is preserved. Only a complete fence
 * produced in the canonical shape changes attribution; a user typing
 * `<<<something_deadbeef` in ordinary prose must not make the rest of their
 * message disappear. Scanning continues after such a fake opening so a real
 * fenced block later in the same episode cannot hide behind it.
 */
export function speakerAttributedContent(content: string): string {
  const out: string[] = [];
  const open = /<<<([A-Za-z][\w-]{0,63})_([0-9a-f]{12})(?: — [^\n]*)?\n/g;
  let emittedUntil = 0;
  let searchFrom = 0;

  while (true) {
    open.lastIndex = searchFrom;
    const match = open.exec(content);
    if (match === null) break;

    const marker = match[0]!;
    const label = match[1]!;
    const nonce = match[2]!;
    const bodyStart = match.index + marker.length;
    const close = `\n${label}_${nonce}>>>`;
    const closeAt = content.indexOf(close, bodyStart);
    if (closeAt < 0) {
      searchFrom = bodyStart;
      continue;
    }

    out.push(content.slice(emittedUntil, match.index));
    if (SPEAKER_FENCE_LABELS.has(label)) out.push(content.slice(bodyStart, closeAt));
    emittedUntil = closeAt + close.length;
    searchFrom = emittedUntil;
  }

  out.push(content.slice(emittedUntil));
  return out.join('').replace(/\n{3,}/g, '\n\n').trim();
}
